apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-app
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: email@email.com
    privateKeySecretRef:
      name: letsencrypt-sock
    solvers:
    - http01:
        ingress:
          class: nginx
